### ISSUE TITLE
JOSS Review Manuscript Editing

### ISSUE THREAD

**Issue by ncborcherding** [Qile0317/scballpack#10]
Hey @Qile0317 

Can you go through the manuscript and just grammar/spell check things? I am finding just small issues, but that is one of the reviewer criterias

Example:
<img width="321" alt="Screenshot 2024-06-26 at 10 11 47 AM" src="https://github.com/Qile0317/APackOfTheClones/assets/22754118/483e8cc4-966a-4375-931a-58c8bcb3c1ef">

Nick

**Comment by Qile0317** [comment]
Just used cspell to fix all the spelling mistakes it could spot on the joss branch in `joss/paper.md`, and after looking through most of the writing I believe the major issues are all fixed. Closing and continuing the discussion on the JOSS review.
