### ISSUE TITLE
Review notes: L20-22 [Nitpick]

### ISSUE THREAD

**Issue by skanwal** [Qile0317/scballpack#11]
From @jspaezp

I do not believe this statement should be part of the summary. I would encourage moving it to the statement of need (and paraphrase accordingly). [Revision: Same as the authors mention in the source code of the paper]

**Comment by Qile0317** [comment]
I believe [052bc06](https://github.com/Qile0317/APackOfTheClones/commit/052bc069ff57c66f2563c9f402a4b809a036462d) was a decent attempt at redoing this part. A new issue can be opened otherwise.
