### ISSUE TITLE
Review notes: L42 [Suggestion]

### ISSUE THREAD

**Issue by skanwal** [Qile0317/scballpack#13]
From @jspaezp:

I do not believe this sentence conveys the value provided by the package. I would appreciate a simple example (For example, depicting clones as contour lines does not allow the identification of xxx which would be clear in our viz because of yyy, as seen in Fig 1.)

**Comment by Qile0317** [comment]
@jspaezp let me know what you think of the new addition

**Comment by Qile0317** [comment]
@jspaezp Wrote a reminder in the joss thread, but will close this for now unless you'd want more changes.

**Comment by jspaezp** [comment]
Yeah It looked fine, I was waiting to see if the other issues would be addressed at the same time

**Comment by Qile0317** [comment]
> Yeah It looked fine, I was waiting to see if the other issues would be addressed at the same time

Ah ok, yeah I was still thinking about how to address the code and data insertion. I can simply include the code and give instructions on how to get the data although it probably won't be enough info for full replication. It was actually pulled from one of nick borcherdings linked google drive files for scRepertoire which I doubt is a good idea in a paper.

The alternative is to link the doc site but I thought that it might change in the future too, so my current idea is to include it in the package vignette on CRAN and link that - what do you think? This probably would cause the version to be bumped again to 1.3.0 though

**Comment by jspaezp** [comment]
I think thats a solid idea ... Ive also seen in the past making an "appendix repo" (new repo only for data) and have the permalink as the source of data. Any of the options sounds great to me (zenodo, cran, bin data, appendix repo)

**Comment by Qile0317** [comment]
Actually yeah, an appendix repo does seem to be the best option as it's the most flexible. I think I'll make it, add some info, and make a release and reference the release. I'll let you know when that's set up

**Comment by Qile0317** [comment]
@jspaezp made and added a supplemental repo with link in the paper. Please open new issue for anything you'd change.
