### ISSUE TITLE
Review notes: General

### ISSUE THREAD

**Issue by skanwal** [Qile0317/scballpack#15]
I would appreciate a code snippet to generate the figure. [Revision: After reading the code referenced I believe you agree, I would also add the data loading to the snippet or reference to a documentation site on how to generate it, I believe this is the example in the landing page of the doc site]

- should I write about other novelty features - customizing, highlighting, clone links?
- maybe an "implementation details" section about how the user can store "runs" of this plot with different parameters and manually customize them?

I don’t believe that highlighting those features is strictly required (Although I would encourage a link to a documentation site with those examples)

**Comment by Qile0317** [comment]
closing for now by adding supplemental repo for figure generation
